"""Type stubs for the Steward native extension."""

from typing import Optional, List, Dict
from enum import Enum

class LensType(Enum):
    DignityInclusion = ...
    BoundariesSafety = ...
    RestraintPrivacy = ...
    TransparencyContestability = ...
    AccountabilityOwnership = ...

class RuleResult(Enum):
    Satisfied = ...
    Violated = ...
    Uncertain = ...
    NotApplicable = ...

class EvidenceSource(Enum):
    Contract = ...
    Output = ...
    Context = ...
    Metadata = ...

class Evidence:
    @property
    def source(self) -> EvidenceSource: ...
    @property
    def description(self) -> str: ...
    @property
    def pointer(self) -> str: ...

class RuleEvaluation:
    @property
    def rule_id(self) -> str: ...
    @property
    def rule_text(self) -> str: ...
    @property
    def result(self) -> RuleResult: ...
    @property
    def evidence(self) -> List[Evidence]: ...
    @property
    def rationale(self) -> str: ...

class LensState:
    def is_pass(self) -> bool: ...
    def is_escalate(self) -> bool: ...
    def is_blocked(self) -> bool: ...
    @property
    def reason(self) -> Optional[str]: ...
    @property
    def violation(self) -> Optional[str]: ...

class LensFinding:
    @property
    def lens(self) -> LensType: ...
    @property
    def question_asked(self) -> str: ...
    @property
    def state(self) -> LensState: ...
    @property
    def rules_evaluated(self) -> List[RuleEvaluation]: ...
    @property
    def confidence(self) -> float: ...

class LensFindings:
    @property
    def dignity_inclusion(self) -> LensFinding: ...
    @property
    def boundaries_safety(self) -> LensFinding: ...
    @property
    def restraint_privacy(self) -> LensFinding: ...
    @property
    def transparency_contestability(self) -> LensFinding: ...
    @property
    def accountability_ownership(self) -> LensFinding: ...
    def all(self) -> List[LensFinding]: ...

class BoundaryViolation:
    @property
    def lens(self) -> LensType: ...
    @property
    def rule_id(self) -> str: ...
    @property
    def rule_text(self) -> str: ...
    @property
    def evidence(self) -> List[Evidence]: ...
    @property
    def accountable_human(self) -> str: ...

class State:
    def is_proceed(self) -> bool: ...
    def is_escalate(self) -> bool: ...
    def is_blocked(self) -> bool: ...
    @property
    def summary(self) -> Optional[str]: ...
    @property
    def uncertainty(self) -> Optional[str]: ...
    @property
    def decision_point(self) -> Optional[str]: ...
    @property
    def options(self) -> Optional[List[str]]: ...
    @property
    def violation(self) -> Optional[BoundaryViolation]: ...

class Contract:
    @staticmethod
    def from_yaml(yaml: str) -> "Contract": ...
    @staticmethod
    def from_yaml_file(path: str) -> "Contract": ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def purpose(self) -> str: ...
    @property
    def accountable_human(self) -> str: ...

class Output:
    @staticmethod
    def text(content: str) -> "Output": ...
    @property
    def content(self) -> str: ...

class EvaluationResult:
    @property
    def state(self) -> State: ...
    @property
    def lens_findings(self) -> LensFindings: ...
    @property
    def confidence(self) -> float: ...
    @property
    def evaluated_at(self) -> str: ...
    def is_proceed(self) -> bool: ...
    def is_escalate(self) -> bool: ...
    def is_blocked(self) -> bool: ...
    @property
    def summary(self) -> Optional[str]: ...
    @property
    def decision_point(self) -> Optional[str]: ...
    @property
    def violation(self) -> Optional[BoundaryViolation]: ...
    def to_json(self) -> str: ...

class EvaluationError(Exception): ...
class ContractError(Exception): ...

def evaluate(contract: Contract, output: Output) -> EvaluationResult: ...
def evaluate_with_context(
    contract: Contract,
    output: Output,
    context: Optional[List[str]] = None,
    metadata: Optional[Dict[str, str]] = None,
) -> EvaluationResult: ...
